name: Python Test


on: [push]


jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Test the Python script "test.py"
        run: python test.py
